### ISSUE TITLE
Исправте страницу с инструкциями по установке

### ISSUE THREAD

**Issue by torchwood01** [DeskChan/DeskChan#14]
Вот это криво:

`$ pacman -S jdk8-openjdk java-openjfx stalonetray libappindicator
$ yaourt launch4j`

Должно быть вот так:

`# pacman -S jdk8-openjdk java-openjfx stalonetray libappindicator
$ yaourt -S launch4j`

**Comment by CORRUPTOR2037** [comment]
Исправил
