### ISSUE TITLE
Где тесты?

### ISSUE THREAD

**Issue by AnkBurov** [DeskChan/DeskChan#17]
![image](https://user-images.githubusercontent.com/5352029/34319511-1afc383a-e7f5-11e7-9290-8aa65069621f.png)

Проект без тестов есть мертворожденный проект, который быстро становится снежным шаром из багов в котором все разваливается быстрее, чем запиливается.

**Comment by CORRUPTOR2037** [comment]
У нас есть тестирование частей программы, лежит оно внутри кода, а не в отдельной папке.
В основном они в этом модуле: https://github.com/DeskChan/DeskChan/tree/master/src/main/java/info/deskchan/speech_command_system.
К сожалению, у нас нет специалистов, которые бы знали, как правильно организовывать и настраивать юнит-тесты. Если вы относитесь к таким, мы были бы рады, если бы вы сделали парочку таких у нас в проекте.

**Comment by AnkBurov** [comment]
> У нас есть тестирование частей программы, лежит оно внутри кода, а не в отдельной папке.
> В основном они в этом модуле: https://github.com/DeskChan/DeskChan/tree/master/src/main/java/info/deskchan/speech_command_system

Это не тесты, а какая-то дрисня. Нормальные тесты запускаются вручную или через test таску, не требуют никакой настройки и действий вне тест воркфлоу (наличие докера - исключение) и проверяют, что все работает как надо. То есть запускаются перед каждым билдом или после каждого коммита в ПРах. Без этого любой проект больше пары тысяч строк кода это снежный шар и карточный домик, особенно если проект в попенсурсе, где ты охуеешь руками тестить каждый пуллреквест.

> К сожалению, у нас нет специалистов, которые бы знали, как правильно организовывать и настраивать юнит-тесты.

Ты траллишь там, чи шо? Хули там уметь в простой junit. Берешь и делаешь просто и без задней мысли. Если тестов дохуя, то прикручиваешь testng и хуячишь в параллель. 
Но конкретно здесь просто юнит-тестов уже недостаточно.

>  Если вы относитесь к таким, мы были бы рады, если бы вы сделали парочку таких у нас в проекте.

Я дам тебе удочку, а не рыбу - будет полезнее. На модули и куски модулей пишешь юнит-тесты. На саму приложуху пилишь интеграционные тесты через любой фреймворк для javafx - запустить говно, ткнуть туда, проверить результат. Ну и сделай еще тест с полной сборкой в докере - экстендишься от нужной оси, засовываешь приложуху в контейнер, билдишь и запускаешь. Для запуска в докере используй testcontainers. В самом тесте или по процессам контейнера проверяй, что дрисня запустилась, или из логов вытаскивай строку, что приложение запустилось и в логе нету исключений. Или опционально можешь сделать, чтобы для теста в докере приложуха запускалась с сервлетом, который будет наружу выставлять только get /health, который изнутри приложухи будет проверять, что все запустилось корректно, а в самом тесте дергать сей рест и чекать ответ. Как сделаешь - прикручиваешь travic ci (бейдж не забудь) и пануешь. 

Давай делай, чтобы нормально было. 
![image](https://user-images.githubusercontent.com/5352029/34319874-86f7e356-e7fd-11e7-8fa1-fedbb9855030.png)

**Comment by CORRUPTOR2037** [comment]
Ну вот на всё, что ты мне тут понаписал, мне придётся потратить месяц. А я и так уже все остальные дела просрочить три раза успел. Я своё уже отгрохал, спасибо.
Ты последний пост не читал? Почитай.
1. Действующих программистов в проекте - 0.
2. Проект общественный. Хочется что-то сделать - делай сам.

**Comment by AnkBurov** [comment]
> Ну вот на всё, что ты мне тут понаписал, мне придётся потратить месяц.

Если ты хочешь стать разработчиком и продвинуться дальше июня - без этого никуда. И без этого проект однозначно провалится. Впрочем, он никуда и не собирался - но как сама идея и даже что-то было запилено в учебных целях - малаца. 
> Действующих программистов в проекте - 0.

Сочувствую вашему горю. 
> Проект общественный. Хочется что-то сделать - делай сам.

Ты неправильно понимаешь смысл попенсорса. Попенсорс это когда люди делают то, что им всем нужно. Это не "пацаны, короч вкидываем в попенсорс, а дальше какие-то лохи за нас все сами сделают", как недавно кажется Майкрософт пушкарнули.

**Comment by CORRUPTOR2037** [comment]
Я тянул почти в одного этот проект с мая и написал для него 23к строк кода, хотя первоначально я подписывался только на разработку модуля общения и больше вообще нихера не умею. Вот пока сюда кто-нибудь ещё не придёт, кроме меня, я ни строчки кода больше не напишу.

**Comment by CORRUPTOR2037** [comment]
Ну при всём уважении
Когда вот так приходят в полностью волонтёрский проект и в максимально вальяжной форме говорят: так, бросай все свои дела, учёбу/работу, все свои планы на проект (а планы-то есть, на нас помимо тестов жалуются ещё на целую кучу вопросов типа: "а чо у вас нет ИИ", "а чо у вас нет анимации", "а чо она ничего не умеет") и беги делать нужные одному мне тесты. Причём эти тесты должны устраивать лично меня, так что ты сейчас перечитаешь пару-тройку документаций по фреймворкам и сразу же их прикрутишь и ещё красиво оформишь!
Ну вот после этого какой реакции можно ожидать? Ну, либо делайте сами, либо становитесть в очередь. Долгую очередь.

**Comment by gunmetal313** [comment]
Я пишу тесты сейчас.

**Comment by gunmetal313** [comment]
https://travis-ci.org/gunmetal313/DeskChan

https://github.com/gunmetal313/DeskChan/tree/add_junit_and_travis
