### ISSUE TITLE
Окно не меняет размеры после изменения шрифта

### ISSUE THREAD

**Issue by PsiHamster** [DeskChan/DeskChan#49]
1. Меняем размер шрифта.
ОР: Окно меняет размеры
ФР: Окно остается таким же

![2018-06-10_01-56-45](https://user-images.githubusercontent.com/8936339/41196045-a92572e4-6c51-11e8-9985-0e93af2b9742.gif)

**Comment by CORRUPTOR2037** [comment]
Пофиксить это в рамках JavaFX не думаю, что реально, там проблемы с вычислением размеров окна.
Можно закрывать окно через Alt+F4 и открывать снова, тогда размер становится нормальным.
Сделаю авто-перезапуск окна в следующий раз.

**Comment by CORRUPTOR2037** [comment]
Исправлено через авто-перезапуск
