### ISSUE TITLE
Кнопка назад не меняет подсветку текущего пункта меню.

### ISSUE THREAD

**Issue by PsiHamster** [DeskChan/DeskChan#50]
1. Заходим в любой из пунктов меню
2. Возвращаемся назад

ОР: Подсветка в боковом меню поменялась
ФР: Нет.

![2018-06-10_02-03-42](https://user-images.githubusercontent.com/8936339/41196100-874d47d6-6c52-11e8-9ece-6a928bfc81a3.gif)

**Comment by CORRUPTOR2037** [comment]
Исправлено
