### ISSUE TITLE
[feature request] Отключать рандомные фразы во время сценария

### ISSUE THREAD

**Issue by PsiHamster** [DeskChan/DeskChan#56]
Добавить возможность выключить случайные сообщения во время сценария / всегда отключать их
![java_2018-06-11_02-27-25](https://user-images.githubusercontent.com/8936339/41206681-4682922c-6d21-11e8-8561-c5642ce1a219.png)

**Comment by CORRUPTOR2037** [comment]
Они навсегда выключены во время сценария. Можно это исправить, понизив приоритет сценария.
