### ISSUE TITLE
При срабатывании будильника органайзера неправильно выводится текст в облачке персонажа

### ISSUE THREAD

**Issue by Leonovers** [DeskChan/DeskChan#64]
При срабатывании будильника в облачке персонажа пишется phrase ALARM, очевидно что так быть не должно.

**Comment by Braklord** [comment]
Т.е. в organizer.phrases ДЧ использует <intent> вместо <text>? Даже если характер поменяешь?

**Comment by CORRUPTOR2037** [comment]
Исправлено
